### ISSUE TITLE
[Spark3] NoClassDefFound for jpr_01

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#154]
```
%dpl
index=example earliest="2020-01-01T00:00:00+02:00" | regex _raw = "^8.*$" 
```

results in
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.teragrep.jpr_01.JavaPcre$LibJavaPcre
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:694)
	at com.sun.jna.Native.getLibraryOptions(Native.java:764)
	at com.sun.jna.Native.getStructureAlignment(Native.java:856)
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at com.teragrep.jpr_01.JavaPcre$LibJavaPcre$OptionsStruct.<init>(JavaPcre.java:42)
	at com.teragrep.jpr_01.JavaPcre.<init>(JavaPcre.java:176)
	at com.teragrep.pth10.ast.commands.transformstatement.regex.RegexMatch.call(RegexMatch.java:69)
```

**Comment by StrongestNumber9** [comment]
Fixed by installing pcre2 packages on the executor nodes
