### ISSUE TITLE
[Spark3] Kafka save does not find kafka data source

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#155]
```
%dpl
index=1k_multi_uniq earliest="2023-06-06T00:00:00"
| teragrep exec kafka save "1k-multi-uniq-test"
```

results in

```
org.apache.spark.sql.AnalysisException: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.failedToFindKafkaDataSourceError(QueryCompilationErrors.scala:1487)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:645)
	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:367)
	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:249)
	at com.teragrep.pth10.ast.DPLInternalStreamingQueryListener.registerQuery(DPLInternalStreamingQueryListener.java:235)
	at com.teragrep.pth10.steps.teragrep.TeragrepKafkaOperations.saveDataToKafka(TeragrepKafkaOperations.java:261)
	at com.teragrep.pth10.steps.teragrep.TeragrepStep.get(TeragrepStep.java:103)
	at com.teragrep.pth10.ast.StepList.executeFromStep(StepList.java:180)
	at com.teragrep.pth10.ast.StepList.execute(StepList.java:150)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:285)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3070)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:170)
```

Is the org.apache.kafka package required to be included in spark 3.x? Currently it is in `test` scope.

**Comment by eemhu** [comment]
need to check spark3 qa configurations as well
