### ISSUE TITLE
ArithmeticException: long overflow in relative time search

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#158]
```sh
index=x latest=-3644444444444444d
```
or
```sh
index=x earliest=-3644444444444444d
```

causes

```sh
java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at java.time.Instant.plus(Instant.java:860)
	at com.teragrep.pth10.ast.Util.addTimeToInstant(Util.java:138)
	at com.teragrep.pth10.ast.Util.relativeTimeModifier(Util.java:223)
	at com.teragrep.pth10.ast.commands.logicalstatement.TimeStatement.timeQualifierEmitXml(TimeStatement.java:216)
<snip>
```

**Comment by eemhu** [comment]
internal PR submitted

**Comment by StrongestNumber9** [comment]
Seems like the internal PR did not fix the issue
As an extra, running something like `index=x earliest=-999999999y` will end up `org.apache.spark.sql.streaming.StreamingQueryException: SQL <snip> Truncated incorrect datetime value: '169089589-04-28'`
