### ISSUE TITLE
NPE on empty search statement

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#176]
**Describe the bug**
```
java.lang.NullPointerException
	at com.teragrep.pth10.ast.commands.logicalstatement.LogicalStatementXML.visitSearchTransformationRoot(LogicalStatementXML.java:132)
	at com.teragrep.pth10.ast.commands.logicalstatement.LogicalStatementXML.visitLogicalStatementXML(LogicalStatementXML.java:116)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitSubsearchTransformStatement(DPLParserCatalystVisitor.java:349)
```
 
**Expected behavior**
no results, not NPE
 
**How to reproduce**
run query
```
%dpl

| makeresults count=1 | eval a=1 | join a [search]
```

 
**Screenshots**

 
**Software version**
com.teragrep-pth_07-5.14.0.4.gcbf4a326.x86_64-1330.x86_64
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
Internal pull request submitted, please review

**Comment by kortemik** [comment]
commit 7d5029e7cac9c3486e1838b0d74f99f130b41c55 ok, pr had another fix that should have it's own pr

**Comment by eemhu** [comment]
removed unnecessary commit from pr

**Comment by eemhu** [comment]
Merged to internal dpl2 branch
