### ISSUE TITLE
NullPointerException when no field/keyword provided for join

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#177]
**Describe the bug**

```sh
java.lang.NullPointerException
	at com.teragrep.pth10.steps.join.JoinStep.get(JoinStep.java:151)
	at com.teragrep.pth10.ast.StepList.executeFromStep(StepList.java:180)
	at com.teragrep.pth10.ast.StepList.execute(StepList.java:150)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:285)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3070)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:185)
	at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:159)
	at org.apache.zeppelin.interpreter.AbstractInterpreter.interpret(AbstractInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:110)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:860)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:752)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
``` 

**Expected behavior**

```sh
<nice message how can't join without field> 
```

**How to reproduce**

```sh
| makeresults count=2000000 | join [makeresults count=2000000|makeresults count=2000000]
```
 
**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
Added a user-friendly error message when the field is not provided in the command.
`be2d7f6e810827f39aa4fd0b2cbb67d0523dcd56`
