### ISSUE TITLE
First search in subsearch is ignored

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#178]
**Describe the bug**

 ```sh
java.lang.RuntimeException: SubsearchStep doesn't have any steps to execute!
	at com.teragrep.pth10.steps.subsearch.SubsearchStep.get(SubsearchStep.java:80)
	at com.teragrep.pth10.steps.join.JoinStep.get(JoinStep.java:77)
	at com.teragrep.pth10.ast.StepList.executeFromStep(StepList.java:180)
	at com.teragrep.pth10.ast.StepList.execute(StepList.java:150)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:285)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3070)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:185)
	at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:159)
	at org.apache.zeppelin.interpreter.AbstractInterpreter.interpret(AbstractInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:110)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:860)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:752)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Expected behavior**

Query to be executed as expected
 
**How to reproduce**

```sh
| makeresults | join partition [makeresults count=1]
```
 
**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
Fix for #169 also fixed this issue
