### ISSUE TITLE
NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#188]
**Describe the bug**

Query fails with `java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply(Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/catalyst/encoders/ExpressionEncoder;`

**Expected behavior**

Works as expected
 
**How to reproduce**

```sh
%dpl
| teragrep get system version
``` 
->
```sh
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply(Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/catalyst/encoders/ExpressionEncoder;
	at com.teragrep.pth10.datasources.GeneratedDatasource.constructStream(GeneratedDatasource.java:116)
	at com.teragrep.pth10.steps.teragrep.TeragrepInfoOperations.getTeragrepVersionAsDataframe(TeragrepInfoOperations.java:82)
	at com.teragrep.pth10.steps.teragrep.TeragrepStep.get(TeragrepStep.java:80)
	at com.teragrep.pth10.ast.StepList.executeFromStep(StepList.java:180)
	at com.teragrep.pth10.ast.StepList.execute(StepList.java:150)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:285)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3070)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:170)
	at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:155)
	at org.apache.zeppelin.interpreter.AbstractInterpreter.interpret(AbstractInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:110)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:860)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:752)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Screenshots**

 
**Software version**

Spark3 version of pth_07/pth_10
`com.teragrep-pth_07-5.9.2.58.g5fc3d232`
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

Tested in Spark3 QA environment

**Comment by StrongestNumber9** [comment]
Seems to be related to #190
