### ISSUE TITLE
providing only subsearch causes NPE

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#194]
**Describe the bug**
```
java.lang.NullPointerException
	at com.teragrep.pth10.ast.commands.logicalstatement.LogicalStatementXML.visitLogicalStatementXML(LogicalStatementXML.java:116)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitSearchTransformationRoot(DPLParserCatalystVisitor.java:318)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:271)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3079)
```
 
**Expected behavior**
should work
 
**How to reproduce**
```
%dpl

[| makeresults count=5| format]
```
 
**Screenshots**

 
**Software version**
pth_10 4.16.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
internal PR submitted
