### ISSUE TITLE
Aggregation command earliest and latest throw NullPointerException if no data

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#233]
**Describe the bug**

No data generates NullPointerException.
```
org.apache.spark.sql.streaming.StreamingQueryException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 4 times, most recent failure: Lost task 0.3 in stage 9.0 (TID 13, xxx, executor 21): java.lang.NullPointerException
	at com.teragrep.pth10.ast.commands.aggregate.UDAFs.BufferClasses.TimestampMapBuffer.earliest(TimestampMapBuffer.java:131)
	at com.teragrep.pth10.ast.commands.aggregate.UDAFs.EarliestLatestAggregator_String.finish(EarliestLatestAggregator_String.java:92)
	at com.teragrep.pth10.ast.commands.aggregate.UDAFs.EarliestLatestAggregator_String.finish(EarliestLatestAggregator_String.java:58)
```
 
**Expected behavior**

Should return no data, but also no exception.
 
**How to reproduce**

Try running earliest or latest to no rows.
 
**Screenshots**

 
**Software version**

4.17.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
internal pr created

**Comment by 51-code** [comment]
Internal pr reviewed
