### ISSUE TITLE
| teragrep exec hdfs load filename returns NPE with "empty" avro files

### ISSUE THREAD

**Issue by nwellingk** [teragrep/pth_10#268]
**Describe the bug**
I tried to load a saved avro file to see its contents and got following:

java.lang.NullPointerException
	at org.apache.zeppelin.interpreter.InterpreterOutput.write(InterpreterOutput.java:334)
	at org.apache.zeppelin.interpreter.InterpreterResult.add(InterpreterResult.java:90)
	at org.apache.zeppelin.interpreter.InterpreterResult.<init>(InterpreterResult.java:75)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:209)
...
 
**Expected behavior**
Query should produce 0 results.
 
**How to reproduce**
Save empty result set as avro, files contain headers only. 
 
**Screenshots**

 
**Software version**
pth_10 5.3.0, pth_07 5.23.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by 51-code** [comment]
Internal PR created.
