### ISSUE TITLE
| teragrep exec hdfs save RuntimeException

### ISSUE THREAD

**Issue by 51-code** [teragrep/pth_10#33]
ID <460>
Reporter <@51-code>

index=xyz earliest="01/01/2017:00:00:00"
| teragrep exec hdfs save abc overwrite=true

results in an error with the following stacktrace:

java.lang.RuntimeException: Error deserializing metadata object: java.io.InvalidClassException: com.teragrep.pth10.ast.commands.transformstatement.teragrep.HdfsSaveMetadata; local class incompatible: stream classdesc serialVersionUID = -2536230522276404688, local class serialVersionUID = 2488500414571191925
at com.teragrep.pth10.steps.teragrep.TeragrepHdfsOperations.deserializeMetadata(TeragrepHdfsOperations.java:532)
at com.teragrep.pth10.steps.teragrep.TeragrepHdfsOperations.saveDataToHdfs(TeragrepHdfsOperations.java:117)
at com.teragrep.pth10.steps.teragrep.TeragrepStep.get(TeragrepStep.java:90)
at com.teragrep.pth10.ast.StepList.executeFromStep(StepList.java:180)
at com.teragrep.pth10.ast.StepList.execute(StepList.java:150)
at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:285)
at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3070)
at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:168)
at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:152)
at org.apache.zeppelin.interpreter.AbstractInterpreter.interpret(AbstractInterpreter.java:47)
at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:110)
at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:860)
at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:752)
at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

**Comment by eemhu** [comment]
related to #35
