### ISSUE TITLE
per_{second,hour,day,minute} throws NPE

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#89]
ID <485>
Reporter <@JohnJacobGuy>

Search:

%dpl
index=products
| rex4j field=_raw "product=(?<product>[\w]+)"
| rex4j field=_raw "sales=(?<sales>-?\d+)"
| timechart span=1sec per_second(sales) by product

Throws

ava.lang.NullPointerException
	at com.teragrep.pth10.ast.commands.aggregate.AggregateFunction.AggregateFunctionEmitCatalyst(AggregateFunction.java:134)
	at com.teragrep.pth10.ast.commands.aggregate.AggregateFunction.visitAggregateFunction(AggregateFunction.java:124)
	at com.teragrep.pth10.ast.commands.transformstatement.TimechartTransformation.visitAggregateFunction(TimechartTransformation.java:222)
	at com.teragrep.pth10.ast.commands.transformstatement.TimechartTransformation.visitAggregateFunction(TimechartTransformation.java:74)
	at com.teragrep.pth_03.antlr.DPLParser$AggregateFunctionContext.accept(DPLParser.java:12752)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth10.ast.commands.transformstatement.TimechartTransformation.timechartTransformationEmitCatalyst(TimechartTransformation.java:147)
	at com.teragrep.pth10.ast.commands.transformstatement.TimechartTransformation.visitTimechartTransformation(TimechartTransformation.java:117)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTimechartTransformation(TransformStatement.java:258)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTimechartTransformation(TransformStatement.java:70)
	at com.teragrep.pth_03.antlr.DPLParser$TimechartTransformationContext.accept(DPLParser.java)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.transformStatementEmitCatalyst(TransformStatement.java:196)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:169)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:70)
	at com.teragrep.pth_03.antlr.DPLParser$TransformStatementContext.accept(DPLParser.java:6602)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.transformStatementEmitCatalyst(TransformStatement.java:217)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:169)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:70)
	at com.teragrep.pth_03.antlr.DPLParser$TransformStatementContext.accept(DPLParser.java:6602)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.transformStatementEmitCatalyst(TransformStatement.java:217)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:169)
	at com.teragrep.pth10.ast.commands.transformstatement.TransformStatement.visitTransformStatement(TransformStatement.java:70)
	at com.teragrep.pth_03.antlr.DPLParser$TransformStatementContext.accept(DPLParser.java:6602)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitTransformStatement(DPLParserCatalystVisitor.java:401)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:278)
	at com.teragrep.pth10.ast.DPLParserCatalystVisitor.visitRoot(DPLParserCatalystVisitor.java:80)
	at com.teragrep.pth_03.antlr.DPLParser$RootContext.accept(DPLParser.java:3069)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:168)
	at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:152)
	at org.apache.zeppelin.interpreter.AbstractInterpreter.interpret(AbstractInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:110)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:860)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:752)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

#228

**Comment by ronja-ui** [comment]
Issue is still existing. You can replicate it by using the following example:

````
%dpl
index=sales_inventory earliest=-5y
| rex4j field=_raw "productId=(?<productId>[a-zA-Z0-9]+-[a-zA-Z0-9]+-[a-zA-Z0-9]+-[a-zA-Z0-9]+[a-zA-Z0-9]+)"
| rex4j field=_raw "price=(?<price>[0-9]+.[0-9]+)"
| timechart span=1sec per_second(price) by productId
````
